title: "InfraDiaries"
description: "Your DevOps & SRE Knowledge Base"
theme: minima

# Disable date-based permalinks
permalink: /posts/:title/

# Navigation tabs
header_pages:
  - index.md
  - posts.md
